### ISSUE TITLE
it seems GhostPost can't connect to server

### ISSUE THREAD

**Issue by ghost** [SalmonProject/GhostPost#4]
![ghostpost tip](https://cloud.githubusercontent.com/assets/19257585/18988551/d6d85de0-8739-11e6-8e29-2b256b9a3a56.PNG)

and...
![registration failed](https://cloud.githubusercontent.com/assets/19257585/18988580/f1857984-8739-11e6-8a8e-edc0348b4bec.PNG)

It was screenshotted in last month. Today I trying to use it again, it still tip same error.

![registration failed](https://cloud.githubusercontent.com/assets/19257585/18988813/f5200d24-873a-11e6-8c91-da635c70abfb.PNG)

`telnet salmon.cs.illinois.edu 8443` 

![telnet](https://cloud.githubusercontent.com/assets/19257585/18988994/18623fae-873c-11e6-907e-e53520282c3f.PNG)

Connection failed. 

It seems that GhostPost can't connect to server. I'm Chinese netizen. Maybe this port of the server is blocked by Chinese goverment.

P.S. Because GhostPost is not in Chrome Web Store, I have to open the developer mode for install it.

**Comment by SalmonProject** [comment]
Sorry, server was down - I have it back up, and for the time being, it's wrapped in a script to bring it back up if it crashes, which seems to be happening more freqeuently than we hoped. Hopefully it should be more stable soon!

:-/ sorry about the developer mode thing - I'll register with the Chrome Web Store soon! (I'll report back here when I have).

**Comment by ghost** [comment]
![okay](https://cloud.githubusercontent.com/assets/19257585/19117933/595be504-8b4d-11e6-9371-a85b1246060a.PNG)
It is okay now:)

The thing about developer mode is not your false. Because of Google strict secuity policy, even in developer mode it tip risky.
![developer mode](https://cloud.githubusercontent.com/assets/19257585/19118647/a825a088-8b4f-11e6-910b-0a3e736858ad.PNG)

Even not in developer mode, after I restart Chrome, it disabled Ghostpost. And I can't enable it.
![unsupported](https://cloud.githubusercontent.com/assets/19257585/19118746/fda406bc-8b4f-11e6-8f7a-f5a5ea440816.PNG)

But [store F&Q](https://developer.chrome.com/webstore/publish) said that publish in the Chrome Web Store need pay to Google the developer signup fee.😂
